### ISSUE TITLE
bootstrap Can't load: dashboard

### ISSUE THREAD

**Issue by navneetccna** [nemoxiaolan/ones#3]
Hi,

I just cloned latest commit and get following message 

bootstrap
Can't load: dashboard

Also what is the language conversion in this new version? please explain i want English support.

**Comment by navneetccna** [comment]
I also noticed that in console request to 

http://ones.localhost:7610/socket.io/?EIO=3&transport=polling&t=1487835681243-0

is not working

**Comment by laofahai** [comment]
@navneetccna this version has some bugs now, `Can't load: xxx` maybe caused by some js didn't loaded, check it in the console.

`http://ones.localhost:7610/socket.io/?EIO=3&transport=polling&t=1487835681243-0` not a error, there's a daemon program for exchange data in iframes.

if u want english version, edit the config `default_language: zh-cn` to `en_us` or other, copy the language file and edit it.

notice that this version is not perfect. I'm working on a refactoring version that might be updated later.

Thanks for your attention.

**Comment by navneetccna** [comment]
I checked all the js in console.
There is no error of not loading any js.
I am facing this issue in all modules.

bootstrap
Can't load: dataModel/dataModelField
bootstrap
Can't load: home/commonType

**Comment by laofahai** [comment]
@navneetccna any error in console?

**Comment by navneetccna** [comment]
no i didnt see any error in console. attaching 2 screen shots as well pls check

![image](https://cloud.githubusercontent.com/assets/210475/23314148/b20eef8a-fae6-11e6-9d06-2371c868ee7b.png)

------

![image](https://cloud.githubusercontent.com/assets/210475/23314210/ff2c75e4-fae6-11e6-83ab-e6d25012547f.png)

**Comment by laofahai** [comment]
@navneetccna try using Chrome and see the request: ?s=/home/config/bootstrap

**Comment by navneetccna** [comment]
Error: [$injector:modulerr] Failed to instantiate module ones.frameInnerModule due to:
Error: [$injector:modulerr] Failed to instantiate module localytics.directives due to:
Error: [$injector:nomod] Module 'localytics.directives' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.2/$injector/nomod?p0=localytics.directives
    at http://ones.localhost/ones/bower_components/angular/angular.js:68:12
    at http://ones.localhost/ones/bower_components/angular/angular.js:2187:17
    at ensure (http://ones.localhost/ones/bower_components/angular/angular.js:2111:38)
    at module (http://ones.localhost/ones/bower_components/angular/angular.js:2185:14)
    at http://ones.localhost/ones/bower_components/angular/angular.js:4756:22
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
    at http://ones.localhost/ones/bower_components/angular/angular.js:4757:40
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
http://errors.angularjs.org/1.6.2/$injector/modulerr?p0=localytics.directives&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'localytics.directives'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.2%2F%24injector%2Fnomod%3Fp0%3Dlocalytics.directives%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2187%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2111%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2185%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4756%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4757%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)
    at http://ones.localhost/ones/bower_components/angular/angular.js:68:12
    at http://ones.localhost/ones/bower_components/angular/angular.js:4779:15
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
    at http://ones.localhost/ones/bower_components/angular/angular.js:4757:40
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
    at createInjector (http://ones.localhost/ones/bower_components/angular/angular.js:4662:19)
    at doBootstrap (http://ones.localhost/ones/bower_components/angular/angular.js:1842:20)
    at Object.bootstrap (http://ones.localhost/ones/bower_components/angular/angular.js:1863:12)
http://errors.angularjs.org/1.6.2/$injector/modulerr?p0=ones.frameInnerModule&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20localytics.directives%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'localytics.directives'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.2%2F%24injector%2Fnomod%3Fp0%3Dlocalytics.directives%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2187%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2111%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2185%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4756%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4757%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.2%2F%24injector%2Fmodulerr%3Fp0%3Dlocalytics.directives%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'localytics.directives'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.6.2%252F%2524injector%252Fnomod%253Fp0%253Dlocalytics.directives%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A68%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A2187%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A2111%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A2185%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4756%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A357%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4740%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4757%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A357%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4740%253A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4779%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4757%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4662%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A1842%3A20)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A1863%3A12)
    at http://ones.localhost/ones/bower_components/angular/angular.js:68:12
    at http://ones.localhost/ones/bower_components/angular/angular.js:2187:17
    at ensure (http://ones.localhost/ones/bower_components/angular/angular.js:2111:38)
    at module (http://ones.localhost/ones/bower_components/angular/angular.js:2185:14)
    at http://ones.localhost/ones/bower_components/angular/angular.js:4756:22
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
    at http://ones.localhost/ones/bower_components/angular/angular.js:4757:40
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
http://errors.angularjs.org/1.6.2/$injector/modulerr?p0=localytics.directives&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'localytics.directives'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.2%2F%24injector%2Fnomod%3Fp0%3Dlocalytics.directives%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2187%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2111%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2185%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4756%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4757%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)
    at http://ones.localhost/ones/bower_components/angular/angular.js:68:12
    at http://ones.localhost/ones/bower_components/angular/angular.js:4779:15
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
    at http://ones.localhost/ones/bower_components/angular/angular.js:4757:40
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
    at createInjector (http://ones.localhost/ones/bower_components/angular/angular.js:4662:19)
    at doBootstrap (http://ones.localhost/ones/bower_components/angular/angular.js:1842:20)
    at Object.bootstrap (http://ones.localhost/ones/bower_components/angular/angular.js:1863:12)
http://errors.angularjs.org/1.6.2/$injector/modulerr?p0=ones.frameInnerModule&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20localytics.directives%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'localytics.directives'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.2%2F%24injector%2Fnomod%3Fp0%3Dlocalytics.directives%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2187%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2111%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A2185%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4756%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4757%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.2%2F%24injector%2Fmodulerr%3Fp0%3Dlocalytics.directives%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'localytics.directives'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.6.2%252F%2524injector%252Fnomod%253Fp0%253Dlocalytics.directives%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A68%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A2187%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A2111%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A2185%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4756%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A357%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4740%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4757%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A357%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fones.localhost%252Fones%252Fbower_components%252Fangular%252Fangular.js%253A4740%253A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4779%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4757%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4740%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A4662%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A1842%3A20)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2Fones.localhost%2Fones%2Fbower_components%2Fangular%2Fangular.js%3A1863%3A12)
    at http://ones.localhost/ones/bower_components/angular/angular.js:68:12
    at http://ones.localhost/ones/bower_components/angular/angular.js:4779:15
    at forEach (http://ones.localhost/ones/bower_components/angular/angular.js:357:20)
    at loadModules (http://ones.localhost/ones/bower_components/angular/angular.js:4740:5)
    at createInjector (http://ones.localhost/ones/bower_components/angular/angular.js:4662:19)
    at doBootstrap (http://ones.localhost/ones/bower_components/angular/angular.js:1842:20)
    at Object.bootstrap (http://ones.localhost/ones/bower_components/angular/angular.js:1863:12)
    at http://ones.localhost/ones/lib/function.js:12:25
    at Object.success (http://ones.localhost/ones/lib/i18n.js:50:21)
    at fire (http://ones.localhost/ones/bower_components/jquery/dist/jquery.js:3187:31)
